'''
Some static utterance strings to identify routes.
'''

small_talk_utterances = [
    "how's the weather today.",
    "how are things going.",
    "lovely weather today",
    "the weather is horrendous",
    "let's go to the chippy",
    "did you watch the game last night.",
    "any weekend plans.",
    "what's new with you.",
    "have you seen any good movies lately.",
    "how's your day been so far.",
    "it's been a long day, hasn't it.",
    "any good books you're reading.",
    "what's your favorite coffee spot.",
    "have you tried that new restaurant downtown.",
    "the traffic was crazy this morning!",
    "can you believe how fast this year has gone by.",
    "did you catch that news story about the puppy rescue.",
    "I love your shirt! Where did you get it.",
    "what's your go-to comfort food.",
    "did you hear about the new tech gadget everyone's talking about.",
    "I'm so ready for the weekend. How about you.",
    "isn't it a beautiful day.",
    "do you have any travel plans coming up.",
    "have you been to any good concerts recently.",
    "I'm so over this cold weather. Bring on summer!",
    "have you been to the new cafe around the corner.",
    "did you hear the thunder last night.",
    "do you have a favorite TV show right now.",
    "have you tried that new ice cream flavor.",
    "what a lovely sunset this evening!",
    "isn’t it getting dark earlier these days.",
    "how's your garden coming along.",
    "did you go for a run this morning.",
    "the leaves are starting to change color, aren't they.",
    "have you picked out your Halloween costume yet.",
    "any plans to hit the beach this summer.",
    "have you been keeping up with the latest trends.",
    "what's your favorite holiday.",
    "did you take up any new hobbies recently.",
    "have you heard about the new series everyone's talking about.",
    "what’s your favorite thing about autumn.",
]

sales_utterances=[
    "what are the sales figures for this quarter.",
    "how did we perform in the last month.",
    "can you show me the revenue trends for this year.",
    "what's the average deal size.",
    "who are our top customers by revenue.",
    "do we have any pending deals this week.",
    "how is the sales pipeline looking.",
    "which products are selling the best.",
    "can you provide a sales report for last year.",
    "what's the forecast for next quarter.",
    "how many units have we sold this month.",
    "what's the conversion rate from leads to sales.",
    "are there any upcoming sales meetings.",
    "what's the year-to-date sales growth.",
    "can you list the top-performing sales reps.",
]

ticket_utterances=[
    "how many open support tickets do we have.",
    "can you show me the most recent support requests.",
    "what's the average response time for support tickets.",
    "are there any high-priority issues that need attention.",
    "how many tickets were resolved this week.",
    "can you give me a breakdown of ticket categories.",
    "what's the current backlog of support tickets.",
    "do we have any unresolved issues older than a week.",
    "what's the customer satisfaction rating for recent tickets.",
    "are there any recurring issues reported by customers.",
    "what's the most common type of support request.",
    "can you summarize the tickets resolved in the last 24 hours.",
    "what's the average resolution time for support tickets.",
    "how many tickets have been escalated.",
    "do we have any negative feedback from recent tickets.",
]

invoice_utterances = [
    "can you show me all outstanding invoices.",
    "what's the total amount due for this month.",
    "do we have any overdue invoices.",
    "can you list all invoices sent last week.",
    "how many invoices were paid this quarter.",
    "can you provide a summary of unpaid invoices.",
    "what's the status of invoice #12345.",
    "do we have any invoices waiting for approval.",
    "what's the average payment time for invoices.",
    "can you generate an invoice report for last month.",
    "how much revenue is expected from pending invoices.",
    "are there any disputed invoices.",
    "what's the total invoiced amount this year.",
    "can you provide details on a specific invoice.",
    "how many invoices were generated today.",
]

resume_utterances = [
    "i want the details of a particular applicant."
    "how many job applications have we received this month.",
    "can you show me the latest resumes submitted.",
    "do we have any resumes matching the data scientist role.",
    "what's the average experience level of applicants.",
    "can you filter resumes by skills in Python.",
    "how many applicants are in the final interview stage.",
    "are there any resumes with experience in project management.",
    "can you provide a summary of all open job positions.",
    "what's the most common qualification among applicants.",
    "how many applicants have a master's degree.",
    "can you list resumes submitted in the last two weeks.",
    "are there any candidates with international experience.",
    "what's the diversity breakdown of the current applicants.",
    "can you show me resumes with specific certifications.",
    "how many applications are pending review.",
]